# Generated by Django 3.2.6 on 2021-08-23 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210823_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 22, 36, 9, 429155), verbose_name='date published'),
        ),
    ]
