# Generated by Django 3.2.6 on 2021-08-23 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 22, 41, 7, 105178), verbose_name='date published'),
        ),
    ]
