# Generated by Django 3.2.6 on 2021-08-24 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 10, 39, 21, 423002), verbose_name='date published'),
        ),
    ]
