# Generated by Django 3.2.7 on 2021-09-03 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_location', models.CharField(max_length=200)),
                ('asset_size', models.CharField(max_length=200)),
                ('asset_price', models.CharField(max_length=200)),
                ('asset_rent', models.CharField(max_length=200)),
                ('asset_tenant', models.CharField(max_length=200)),
                ('asset_slug', models.CharField(default=1, max_length=200)),
                ('asset_published', models.DateTimeField(default=datetime.datetime(2021, 9, 3, 10, 44, 14, 551541), verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_type', models.CharField(max_length=200)),
                ('people_name', models.CharField(max_length=200)),
                ('people_surname', models.CharField(max_length=200)),
                ('people_phone_number', models.CharField(max_length=200)),
                ('people_email', models.CharField(max_length=200)),
                ('people_occupation', models.CharField(max_length=200)),
                ('people_revenue', models.CharField(max_length=200)),
                ('people_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorialseries',
            name='tutorial_category',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.DeleteModel(
            name='TutorialCategory',
        ),
        migrations.DeleteModel(
            name='TutorialSeries',
        ),
    ]
